### PR TITLE
Move Banner Up so it does not overlap

### PR DESCRIPTION
**Pull request by wormeyman**
The plugin title.

### CODE REVIEW

**Comment by erayalakese** [comment]
Hello @wormeyman , thank you for patch.

Can you please tell me where is the overlay ? wordpress.org/plugins/slack-integration/ ?

**Comment by wormeyman** [comment]
The I moved it up so it doesn't overlap the plugin name which i highlighted.
image

**Comment by wormeyman** [comment]
According to http://wptavern.com/free-psd-template-for-creating-a-wordpress-org-plugin-banner the preview URL below should work for you but it does not work for me.

https://wordpress.org/plugins/slack-integration/?banner_url=https://raw.githubusercontent.com/wormeyman/slack-wordpress/BannerMoveUp/assets/banner-772x250.png

**Comment by erayalakese** [comment]
ekran resmi 2015-04-08 03 46 30

That preview working great for me. It looking weird because not vertically aligned to middle but it's better than overlap.

**Pull request merged**
