### PR TITLE
Add Icon

### PR DESCRIPTION
**Pull request by wormeyman**
Using Font Awesome House icon like slack. This shouldn't conflict with their branding hopefully.

### CODE REVIEW

**Comment by erayalakese** [comment]
@wormeyman ,

I'm really happy about your helps for this plugin. Thank you.

> This shouldn't conflict with their branding hopefully.

You're using Font-Awesome so it's not about Slack. I just look for Font-Awesome's [license](http://fontawesome.io/license/) and here the message about license : 

image

**Comment by wormeyman** [comment]
:+1: I'm glad I could help.

**Comment by erayalakese** [comment]
@wormeyman  Can you tell me where this icon will appear?

**Comment by wormeyman** [comment]
image

It'll go there when people search.

**Comment by erayalakese** [comment]
Hello @wormeyman ,

I was waiting for answer from Slack developers to use their logo . Because of this I couldn't merge this PR . But thank you for your effort.

**Comment by wormeyman** [comment]
Did they say yes?

**Comment by erayalakese** [comment]
Not yet :) I'll keep this issue open until I got an answer.

**Comment by wormeyman** [comment]
That would be great if you could :smiley:

**Comment by erayalakese** [comment]
Hello @wormeyman ,

If you want to support this plugin on wordpress.org can you please [give a review](https://wordpress.org/support/view/plugin-reviews/slack-integration) ?

Thank you.

**Comment by erayalakese** [comment]
I've uploaded Slack's icon ., you can see it on [search page](https://wordpress.org/plugins/search.php?q=slack).

Thank you for patch !

**Pull request closed without merging**
